/* Interfaz SiasCloud 3.0. Todos los saldos y pagos se validan en el servidor. */
(() => {
  'use strict';
  let A;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const C=window.SiasRetailCore,api=(action,p={})=>A.erpCall(action,p),money=v=>A.money(v),qty=v=>A.fmtQty(v);
  const uid=()=>crypto.randomUUID(),roles={SELLER:'Vendedor',PREPARER:'Preparador',PACKER:'Embalador',CASHIER:'Cajero'};
  const labels={REQUEST:'Solicitud',QUOTE:'Cotización',ORDER:'Pedido',DELIVERY:'Guía',SALE:'Venta',WHOLESALE:'Venta mayorista'};
  const status={DRAFT:'Borrador',POSTED:'Confirmado',VOID:'Anulado',OPEN:'Abierta',CLOSED:'Cerrado'};
  const methods={CASH:'Efectivo',CARD:'Tarjeta',TRANSFER:'Transferencia',CLIENT_CREDIT:'Crédito cliente',OTHER:'Otro'};
  const accountNames={'1100':'Caja','1110':'Bancos / tarjetas','1120':'Clientes por cobrar','1130':'IVA crédito','1200':'Mercaderías','2100':'Proveedores','2110':'IVA débito','2120':'Créditos de clientes','4100':'Ventas'};
  const badge=(s,ok=true)=>`<span class="badge ${ok?'ok':'warn'}">${E(status[s]||s)}</span>`;
  const button=(label,id,primary=false)=>`<button type="button" id="${id}" class="btn ${primary?'primary':'secondary'}">${E(label)}</button>`;
  const options=(rows,value='',empty='Seleccionar…')=>`<option value="">${E(empty)}</option>`+rows.map(x=>`<option value="${E(x.id)}" ${x.id===value?'selected':''}>${E(x.name||x.legal_name)}${x.rut?' · '+E(x.rut):''}</option>`).join('');
  const head=(title,sub,buttons='')=>`<div class="retail-head"><div><h2>${E(title)}</h2><p>${E(sub)}</p></div><div class="retail-actions">${buttons}</div></div>`;
  const empty=(cols,msg='Sin registros')=>`<tr><td colspan="${cols}" class="empty">${E(msg)}</td></tr>`;
  const guarded=fn=>async e=>{const b=e?.currentTarget;try{if(b?.tagName==='BUTTON')A.setBusy(b,true);await fn(e);}catch(err){A.toast(A.errorText(err),true);}finally{if(b?.tagName==='BUTTON'&&b.isConnected)A.setBusy(b,false);}};
  const on=(id,fn)=>$(id)?.addEventListener('click',guarded(fn));
  function readModal(title,html){A.openModal(title,html,async()=>{},'Cerrar');const b=$('#modalActions .primary');b.type='button';b.onclick=()=>A.closeModal(true);$('#modalCancel').classList.add('hidden');}
  function exportCsv(name,headers,rows){const esc=v=>'"'+(/^[=+@\-\t\r]/.test(String(v??''))?"'":'')+String(v??'').replaceAll('"','""')+'"';const url=URL.createObjectURL(new Blob(['\uFEFF'+[headers,...rows].map(r=>r.map(esc).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const pos=()=>window.SiasPos.render();
  async function openCash(){
    const cashiers=(await api('cash.cashiers')).rows||[];
    if(!cashiers.length)throw new Error('Primero crea al menos un responsable activo con la función Cajero');
    const key=uid();
    A.openModal('Abrir caja',`<div class="retail-form"><label>Cajero<select name="cashier_id" required>${options(cashiers,'','Selecciona el cajero…')}</select></label><label>Caja<input name="register_code" maxlength="40" required value="CAJA-1"></label><label>Efectivo de apertura<input name="opening_cash" type="number" min="0" step="1" value="0" required></label><div class="section-note">La sesión, las ventas y los documentos del POS quedarán asociados a este cajero y al usuario autenticado que abrió la caja.</div></div>`,async fd=>{await api('cash.open',{request_key:key,cashier_id:fd.get('cashier_id'),register_code:fd.get('register_code'),opening_cash:Number(fd.get('opening_cash'))});return {toast:'Caja abierta',afterSave:()=>A.state.route==='pos'?pos():cash()};},'Abrir caja');
  }
  async function cash(){
    const r=await api('cash.sessions'),rows=r.rows||[],own=rows.find(s=>s.status==='OPEN'&&s.user_id===A.state.me.user.id);
    $('#content').innerHTML=head('Caja y cierres','Apertura, cajero responsable, movimientos y arqueo separado por medio de pago.',!own&&A.can('POS_MANAGE')?button('Abrir caja','cashOpen',true):button('Volver al POS','cashPos',true))+`<div class="card"><div class="table-wrap"><table><thead><tr><th>Caja</th><th>Cajero</th><th>Usuario operador</th><th>Apertura</th><th>Estado</th><th>Cierre / diferencias</th><th>Acciones</th></tr></thead><tbody>${rows.map(s=>{const dif=s.difference_breakdown||{};const close=s.status==='CLOSED'?`<strong>${E(A.fmtDate(s.closed_at))}</strong><small class="cell-sub">Efectivo ${money(dif.CASH||0)} · Tarjeta ${money(dif.CARD||0)} · Transfer. ${money(dif.TRANSFER||0)}</small>`:'—';return `<tr><td><strong>${E(s.register_code)}</strong><small class="cell-sub">Inicial ${money(s.opening_cash)}</small></td><td><strong>${E(s.cashier?.name||'Cajero histórico sin asignar')}</strong></td><td>${E(s.operator?.full_name||s.operator?.email||'—')}</td><td>${E(A.fmtDate(s.opened_at))}</td><td>${badge(s.status,s.status==='OPEN')}</td><td>${close}</td><td><button type="button" class="btn secondary small" data-cash-summary="${E(s.id)}">Ver arqueo</button>${s.status==='OPEN'&&s.user_id===A.state.me.user.id&&A.can('POS_MANAGE')?` <button type="button" class="btn primary small" data-cash-close="${E(s.id)}">Cerrar</button>`:''}</td></tr>`;}).join('')||empty(7)}</tbody></table></div></div>`;
    on('#cashOpen',openCash);on('#cashPos',()=>A.navigate('pos'));$$('[data-cash-summary]').forEach(b=>b.addEventListener('click',guarded(()=>cashSummary(b.dataset.cashSummary))));$$('[data-cash-close]').forEach(b=>b.addEventListener('click',guarded(()=>closeCash(b.dataset.cashClose))));
  }
  async function cashSummary(id){
    const r=await api('cash.summary',{id}),s=r.session,expected=r.expected_breakdown||{},counted=s.counted_breakdown||{},diff=s.difference_breakdown||{};
    const payRows=['CASH','CARD','TRANSFER'].map(m=>`<tr><td><strong>${E(methods[m])}</strong>${m==='CASH'?'<small class="cell-sub">Incluye apertura + ingresos - retiros</small>':''}</td><td class="right">${money(expected[m]||0)}</td><td class="right">${s.status==='CLOSED'?money(counted[m]||0):'—'}</td><td class="right ${Number(diff[m]||0)<0?'danger-text':Number(diff[m]||0)>0?'positive-text':''}">${s.status==='CLOSED'?money(diff[m]||0):'—'}</td></tr>`).join('');
    readModal(`Arqueo · ${s.register_code}`,`<div class="source-strip"><strong>Cajero: ${E(r.cashier?.name||'Histórico sin asignar')}</strong><span>Operador: ${E(r.operator?.full_name||r.operator?.email||'—')} · Apertura ${E(A.fmtDate(s.opened_at))}${s.closed_at?' · Cierre '+E(A.fmtDate(s.closed_at)):''}</span></div><div class="table-wrap mt"><table class="cash-breakdown-table"><thead><tr><th>Medio</th><th class="right">Esperado</th><th class="right">Declarado</th><th class="right">Diferencia</th></tr></thead><tbody>${payRows}</tbody></table></div><div class="retail-metric-grid mt"><div class="card"><span>Ventas en efectivo</span><strong>${money(r.cash_sales||0)}</strong></div><div class="card"><span>Ingresos manuales</span><strong>${money(r.cash_in||0)}</strong></div><div class="card"><span>Retiros</span><strong>${money(r.cash_out||0)}</strong></div></div><div class="form-section"><h4>Pagos registrados en la sesión</h4><div class="list">${r.methods.map(x=>`<div class="list-item"><span>${E(methods[x.method]||x.method)} · ${x.payments} pagos</span><strong>${money(x.amount)}</strong></div>`).join('')||'<p>Sin pagos registrados.</p>'}</div></div>${s.notes?`<div class="section-note"><strong>Observación de cierre</strong><br>${E(s.notes)}</div>`:''}<div class="retail-actions">${button('Imprimir arqueo','cashPrintSummary')}${s.status==='OPEN'&&s.user_id===A.state.me.user.id&&A.can('POS_MANAGE')?button('Ingreso de efectivo','cashIn')+button('Retiro de efectivo','cashOut'):''}</div>`);
    on('#cashPrintSummary',()=>printCashSummary(r));on('#cashIn',()=>cashMove(id,'IN'));on('#cashOut',()=>cashMove(id,'OUT'));
  }
  async function printCashSummary(r){
    let format='A4';try{const cfg=await api('printing.config.get');format=cfg.formats?.system?.CASH_CLOSE||cfg.formats?.defaults?.system||'A4';}catch{}
    const s=r.session||{},expected=r.expected_breakdown||{},counted=s.counted_breakdown||{},diff=s.difference_breakdown||{},is58=format==='58MM',thermal=format!=='A4',paper=is58?'58mm':thermal?'80mm':'A4',width=is58?'52mm':thermal?'72mm':'186mm',company=(A.state.me.companies||[]).find(c=>c.id===A.state.me.companyId)||{},logo=(company.show_logo_documents!==false&&company.logo_url)?company.logo_url:'';
    const w=window.open('','_blank');if(!w)throw new Error('Habilita ventanas emergentes para imprimir');
    const rows=['CASH','CARD','TRANSFER'].map(m=>`<tr><td>${E(methods[m])}</td><td>${money(expected[m]||0)}</td><td>${s.status==='CLOSED'?money(counted[m]||0):'—'}</td><td>${s.status==='CLOSED'?money(diff[m]||0):'—'}</td></tr>`).join('');
    w.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Arqueo ${E(s.register_code||'')}</title><style>@page{size:${thermal?paper+' auto':'A4 portrait'};margin:${thermal?'0':'12mm'}}*{box-sizing:border-box}body{margin:0;background:#fff;color:#111;font-family:Arial,sans-serif}.toolbar{text-align:center;padding:10px;background:#eef3f9}.toolbar button{border:0;border-radius:8px;background:#2563eb;color:#fff;padding:9px 14px;font-weight:700}.sheet{width:${width};margin:0 auto;padding:${thermal?(is58?'3mm 1.5mm':'4mm 2mm'):'8mm'};font-size:${is58?'8px':thermal?'10px':'12px'}}.company-logo{display:block;max-width:${is58?'34mm':thermal?'48mm':'58mm'};max-height:${is58?'15mm':thermal?'20mm':'26mm'};object-fit:contain;margin:0 auto 3mm}h1{font-size:${is58?'13px':thermal?'16px':'22px'};margin:0 0 3mm;text-align:center}p{line-height:1.45;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;font-size:inherit}th,td{padding:${thermal?'3px 1px':'7px 5px'};border-bottom:1px solid #bbb;text-align:right}th:first-child,td:first-child{text-align:left}.totals{margin-top:3mm;display:grid;gap:4px}.totals div{display:flex;justify-content:space-between}.note{margin-top:3mm;padding-top:2mm;border-top:1px dashed #777;white-space:pre-wrap}.foot{text-align:center;margin-top:4mm;font-size:.85em;color:#555}@media print{.toolbar{display:none}.sheet{margin:0 auto}}</style></head><body><div class="toolbar"><button onclick="window.print()">Imprimir ${paper}</button></div><main class="sheet">${logo?`<img class="company-logo" src="${E(logo)}" alt="Logotipo de ${E(company.trade_name||company.legal_name||'empresa')}">`:''}<h1>Arqueo de caja</h1><p><strong>${E(company.trade_name||company.legal_name||'SiasCloud')}</strong><br>Caja: ${E(s.register_code||'—')}<br>Cajero: ${E(r.cashier?.name||'Histórico sin asignar')}<br>Operador: ${E(r.operator?.full_name||r.operator?.email||'—')}<br>Apertura: ${E(A.fmtDate(s.opened_at))}${s.closed_at?'<br>Cierre: '+E(A.fmtDate(s.closed_at)):''}</p><table><thead><tr><th>Medio</th><th>Esperado</th><th>Declarado</th><th>Diferencia</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>Ventas efectivo</span><strong>${money(r.cash_sales||0)}</strong></div><div><span>Ingresos</span><strong>${money(r.cash_in||0)}</strong></div><div><span>Retiros</span><strong>${money(r.cash_out||0)}</strong></div></div>${s.notes?`<div class="note"><strong>Observación</strong><br>${E(s.notes)}</div>`:''}<div class="foot">SiasCloud · Cierre asociado al cajero y usuario registrados.</div></main></body></html>`);w.document.close();w.focus();
  }
  function cashMove(id,kind){const key=uid();A.openModal(kind==='IN'?'Ingreso de efectivo':'Retiro de efectivo',`<div class="retail-form"><label>Monto<input name="amount" type="number" min="1" step="1" required></label><label>Motivo<textarea name="reason" minlength="5" required></textarea></label></div>`,async fd=>{await api('cash.move',{id,kind,amount:Number(fd.get('amount')),reason:fd.get('reason'),request_key:key});return {toast:'Movimiento de caja registrado'};});}
  async function closeCash(id){
    const r=await api('cash.summary',{id}),key=uid(),expected=r.expected_breakdown||{CASH:r.expected_cash||0,CARD:0,TRANSFER:0};
    const fields=['CASH','CARD','TRANSFER'].map(m=>`<div class="cash-close-row"><div><strong>${E(methods[m])}</strong><small>${m==='CASH'?'Efectivo físico esperado en caja':'Total registrado por el sistema'}</small></div><div><span>Esperado</span><b>${money(expected[m]||0)}</b></div><label>Declarado<input name="counted_${m}" data-close-method="${m}" type="number" min="0" step="1" value="${Number(expected[m]||0)}" required></label><div><span>Diferencia</span><b data-close-diff="${m}">${money(0)}</b></div></div>`).join('');
    A.openModal(`Cerrar ${r.session.register_code}`,`<div class="retail-form"><div class="source-strip"><strong>Cajero: ${E(r.cashier?.name||'Histórico sin asignar')}</strong><span>El cierre se compara por cada medio de pago; no se consolida en una sola cifra.</span></div><div class="cash-close-grid">${fields}</div><div class="settlement-check"><span>Diferencia total de control</span><strong id="closeTotalDifference">${money(0)}</strong></div><label>Observaciones / motivo de diferencias<textarea name="notes" rows="3"></textarea></label></div>`,async fd=>{const counted=Object.fromEntries(['CASH','CARD','TRANSFER'].map(m=>[m,Number(fd.get(`counted_${m}`))]));const totalDiff=['CASH','CARD','TRANSFER'].reduce((n,m)=>n+counted[m]-Number(expected[m]||0),0),notes=String(fd.get('notes')||'').trim();if(Math.abs(totalDiff)>.001&&notes.length<5)throw new Error('Explica el motivo de la diferencia de cierre');await api('cash.close',{id,request_key:key,counted,notes});return {toast:'Caja cerrada con arqueo por medio de pago',afterSave:()=>cash()};},'Cerrar caja');
    const recalc=()=>{let total=0;$$('[data-close-method]').forEach(input=>{const m=input.dataset.closeMethod,d=Number(input.value||0)-Number(expected[m]||0);total+=d;const out=$(`[data-close-diff="${m}"]`);if(out){out.textContent=money(d);out.classList.toggle('danger-text',d<0);out.classList.toggle('positive-text',d>0);}});$('#closeTotalDifference').textContent=money(total);};$$('[data-close-method]').forEach(input=>input.addEventListener('input',recalc));recalc();
  }
  async function movements(){
    const catalog=await api('movements.catalog'),today=localDate(),monthStart=today.slice(0,8)+'01',movementNames={VENTA:'Venta',INGRESO:'Entrada',SALIDA:'Salida',AJUSTE:'Ajuste',TRASLADO_SALIDA:'Traslado salida',TRASLADO_ENTRADA:'Traslado entrada',ANULACION:'Anulación',ANULACION_TRASLADO:'Anulación traslado',APERTURA:'Stock inicial'};
    const userOptions=(catalog.users||[]).map(x=>({id:x.id,name:x.full_name||x.email})),typeOptions=(catalog.movement_types||[]).map(x=>({id:x,name:movementNames[x]||x}));
    $('#content').innerHTML=head('Libro de Movimientos','Historial completo y auditable de entradas, salidas, ventas, ajustes, traslados, documentos, clientes, bodegas, usuarios y cajeros.',button('Exportar CSV','movementExport'))+`<div class="card movement-filter-card"><div class="movement-filters"><label>Desde<input id="movementFrom" type="date" value="${monthStart}"></label><label>Hasta<input id="movementTo" type="date" value="${today}"></label><label>Producto<select id="movementProduct">${options(catalog.products||[],'','Todos los productos')}</select></label><label>Cliente<select id="movementCustomer">${options(catalog.customers||[],'','Todos los clientes')}</select></label><label>Bodega<select id="movementWarehouse">${options(catalog.warehouses||[],'','Todas las bodegas')}</select></label><label>Tipo<select id="movementType">${options(typeOptions,'','Todos los movimientos')}</select></label><label>Dirección<select id="movementDirection"><option value="">Entradas y salidas</option><option value="IN">Entradas</option><option value="OUT">Salidas</option></select></label><label>Estado documento<select id="movementStatus"><option value="">Todos</option><option value="POSTED">Confirmado</option><option value="VOID">Anulado</option><option value="DRAFT">Borrador</option><option value="SIN_DOCUMENTO">Sin documento</option></select></label><label>Usuario<select id="movementUser">${options(userOptions,'','Todos los usuarios')}</select></label><label>Cajero<select id="movementCashier">${options(catalog.cashiers||[],'','Todos los cajeros')}</select></label><label class="movement-doc-filter">Documento / folio<input id="movementDocument" placeholder="Venta, folio DTE, referencia…"></label></div><div class="retail-actions mt">${button('Consultar historial','movementLoad',true)}${button('Limpiar filtros','movementClear')}</div></div><div id="movementMetrics" class="retail-metric-grid"></div><div class="card"><div id="movementWarning"></div><div class="table-wrap movement-table-wrap"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Movimiento</th><th class="right">Cantidad</th><th class="right">Saldo antes</th><th class="right">Saldo después</th><th>Bodega</th><th>Cliente / proveedor</th><th>Documento / DTE</th><th>Responsables</th><th>Estado</th><th>Nota</th><th></th></tr></thead><tbody id="movementRows"></tbody></table></div></div>`;
    let exported=[];
    const load=async()=>{const payload={from:$('#movementFrom').value,to:$('#movementTo').value,product_id:$('#movementProduct').value||null,customer_id:$('#movementCustomer').value||null,warehouse_id:$('#movementWarehouse').value||null,movement_type:$('#movementType').value,status:$('#movementStatus').value,direction:$('#movementDirection').value,user_id:$('#movementUser').value||null,cashier_id:$('#movementCashier').value||null,document_search:$('#movementDocument').value,limit:5000},r=await api('movements.history',payload),rows=r.rows||[];
      // El filtro por cliente se aplica también aquí para no perder la referencia visual en documentos antiguos.
      const customerId=payload.customer_id;const visible=customerId?rows.filter(x=>x.document?.customer_id===customerId):rows;
      $('#movementMetrics').innerHTML=`<div class="card"><span>Registros</span><strong>${visible.length}</strong></div><div class="card"><span>Unidades de entrada</span><strong>${qty(visible.filter(x=>Number(x.quantity)>0).reduce((n,x)=>n+Number(x.quantity||0),0))}</strong></div><div class="card"><span>Unidades de salida</span><strong>${qty(visible.filter(x=>Number(x.quantity)<0).reduce((n,x)=>n+Math.abs(Number(x.quantity||0)),0))}</strong></div><div class="card"><span>Ajustes</span><strong>${visible.filter(x=>String(x.movement_type).includes('AJUSTE')).length}</strong></div>`;
      $('#movementWarning').innerHTML=r.truncated?'<div class="retail-note warn"><strong>Resultado limitado a 5.000 registros.</strong><span>Reduce el rango de fechas o aplica más filtros para una auditoría completa.</span></div>':'';
      $('#movementRows').innerHTML=visible.map(x=>{const qn=Number(x.quantity||0),doc=x.document,dtes=x.dtes||[],counterparty=x.customer||x.supplier,route=x.route,warehouseHtml=route?.from||route?.to?`<strong>${E(route?.from?.name||'—')} → ${E(route?.to?.name||'—')}</strong><small class="cell-sub">Registro en ${E(x.warehouse?.name||'—')}</small>`:E(x.warehouse?.name||'—'),docHtml=doc?`<strong>${E(labels[doc.document_type]||doc.document_type)} · ${E(doc.number)}</strong>${dtes.length?`<small class="cell-sub">${dtes.map(d=>`DTE ${E(d.document_type)} folio ${E(d.folio||'Pendiente')}`).join(' · ')}</small>`:''}`:`<span>${E(x.reference_type||'Sin documento')}</span>${x.reference_id?`<small class="cell-sub" title="${E(x.reference_id)}">Ref. ${E(String(x.reference_id).slice(0,12))}…</small>`:''}`,actors=[`Movimiento: ${x.actor?.full_name||x.actor?.email||'Sistema'}`,doc?.created_by?`Documento: ${x.document_user?.full_name||x.document_user?.email||'Usuario'}`:'',x.cash_operator?`Operador POS: ${x.cash_operator.full_name||x.cash_operator.email||'Usuario'}`:'',x.cashier?`Cajero: ${x.cashier.name}`:'',x.cash_register?`Caja: ${x.cash_register}`:'',...dtes.map(d=>`DTE: ${d.created_by_user?.full_name||d.created_by_user?.email||'Usuario'}`)].filter(Boolean);return `<tr><td>${E(A.fmtDate(x.created_at))}</td><td><strong>${E(x.product?.name||'—')}</strong><small class="cell-sub">${E(x.product?.sku||'')} ${E(x.product?.unit||'')}</small></td><td>${E(movementNames[x.movement_type]||x.movement_type)}</td><td class="right ${qn<0?'danger-text':'positive-text'}">${qn>0?'+':''}${qty(qn)}</td><td class="right">${qty(x.balance_before)}</td><td class="right"><strong>${qty(x.balance_after)}</strong></td><td>${warehouseHtml}</td><td>${counterparty?`<strong>${E(counterparty.legal_name)}</strong><small class="cell-sub">${E(counterparty.rut||'')}</small>`:'—'}</td><td>${docHtml}</td><td>${actors.map(a=>`<small class="movement-actor">${E(a)}</small>`).join('')}</td><td>${doc?badge(doc.status,doc.status==='POSTED'):'<span class="badge ok">REGISTRADO</span>'}</td><td>${E(x.note||'—')}</td><td>${doc?`<button type="button" class="btn secondary small" data-movement-doc="${E(doc.id)}">Ver</button>`:''}</td></tr>`;}).join('')||empty(13,'No hay movimientos para los filtros seleccionados.');
      $$('[data-movement-doc]').forEach(b=>b.addEventListener('click',guarded(()=>window.SiasOperations.preview(b.dataset.movementDoc))));
      exported=visible.map(x=>[A.fmtDate(x.created_at),x.product?.name||'',x.product?.sku||'',movementNames[x.movement_type]||x.movement_type,x.quantity,x.balance_before,x.balance_after,(x.route?.from||x.route?.to)?`${x.route?.from?.name||''} → ${x.route?.to?.name||''}`:(x.warehouse?.name||''),x.customer?.legal_name||x.supplier?.legal_name||'',x.document?.number||x.reference_id||'',(x.dtes||[]).map(d=>`${d.document_type}-${d.folio||''}`).join(' | '),x.actor?.full_name||x.actor?.email||'',x.cashier?.name||'',x.document?.status||'',x.note||'']);
    };
    on('#movementLoad',load);on('#movementClear',async()=>{$('#movementFrom').value=monthStart;$('#movementTo').value=today;for(const id of ['movementProduct','movementCustomer','movementWarehouse','movementType','movementDirection','movementStatus','movementUser','movementCashier'])$("#"+id).value='';$('#movementDocument').value='';await load();});on('#movementExport',()=>exportCsv('SiasCloud_Libro_Movimientos.csv',['Fecha','Producto','SKU','Movimiento','Cantidad','Saldo antes','Saldo después','Bodega','Cliente / proveedor','Documento','DTE','Usuario','Cajero','Estado','Nota'],exported));await load();
  }
  async function credits(){const r=await api('credits.list'),rows=r.rows||[];$('#content').innerHTML=head('Créditos de clientes','Saldos de notas emitidas y sus aplicaciones sucesivas.',(A.can('BILLING_MANAGE')?button('Emitir nota de crédito','creditIssue'):'')+(A.can('CREDIT_MANAGE')?button('Actualizar notas emitidas','creditSync',true):''))+`<div class="retail-metric-grid"><div class="card"><span>Saldo disponible</span><strong>${money(rows.reduce((s,x)=>s+Number(x.balance),0))}</strong></div><div class="card"><span>Créditos con saldo</span><strong>${rows.filter(x=>x.balance>0).length}</strong></div><div class="card"><span>Total aplicado</span><strong>${money(rows.reduce((s,x)=>s+Number(x.original_amount)-Number(x.balance),0))}</strong></div></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Nota / ambiente</th><th>Fecha</th><th class="right">Original</th><th class="right">Disponible</th><th>Acciones</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${E(x.customer?.legal_name)}</strong><small class="cell-sub">${E(x.customer?.rut)}</small></td><td>${E(x.dte?.folio||'')}<small class="cell-sub">${E(x.environment)}</small></td><td>${E(x.dte?.issue_date)}</td><td class="right">${money(x.original_amount)}</td><td class="right credit-balance">${money(x.balance)}</td><td><button type="button" class="btn secondary small" data-credit-history="${E(x.id)}">Historial</button>${x.balance>0&&A.can('CREDIT_MANAGE')?` <button type="button" class="btn primary small" data-credit-apply="${E(x.id)}">Aplicar</button>`:''}</td></tr>`).join('')||empty(6,'Aún no hay créditos registrados.')}</tbody></table></div></div>`;on('#creditSync',async()=>{await api('credits.sync');await credits();A.toast('Notas y saldos actualizados');});on('#creditIssue',()=>window.SiasOperations.directDteModal(61));$$('[data-credit-history]').forEach(b=>b.addEventListener('click',guarded(()=>creditHistory(b.dataset.creditHistory))));$$('[data-credit-apply]').forEach(b=>b.addEventListener('click',guarded(()=>applyCredit(rows.find(x=>x.id===b.dataset.creditApply)))));}
  async function creditHistory(id){const r=await api('credits.history',{credit_id:id});readModal('Aplicaciones del crédito',`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Venta</th><th class="right">Monto aplicado</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${E(A.fmtDate(x.created_at))}</td><td>${E(x.document?.number)}</td><td class="right">${money(x.amount)}</td></tr>`).join('')||empty(3,'El crédito aún no se ha usado.')}</tbody></table></div>`);}
  async function applyCredit(c){const r=await api('documents.list',{customer_id:c.customer_id,limit:500}),rows=r.rows.filter(d=>d.customer_id===c.customer_id&&d.status==='POSTED'&&['SALE','WHOLESALE'].includes(d.document_type)&&d.payment_status!=='PAID'),key=uid();if(!rows.length)throw new Error('El cliente no tiene ventas pendientes. Puedes usar el saldo en una compra nueva desde el POS.');A.openModal('Aplicar crédito a venta',`<div class="retail-form"><div class="pos-total"><span>Saldo disponible</span><strong>${money(c.balance)}</strong></div><label>Venta del mismo cliente<select name="document_id" required>${options(rows.map(d=>({...d,name:`${d.number} · ${money(d.total)}`})))}</select></label><label>Monto a aplicar<input name="amount" type="number" min="1" max="${c.balance}" step="1" required></label></div>`,async fd=>{await api('credits.apply',{credit_id:c.id,document_id:fd.get('document_id'),amount:Number(fd.get('amount')),request_key:key});return {toast:'Crédito aplicado'};});}
  async function staff(){const rows=(await api('staff.list')).rows;$('#content').innerHTML=head('Responsables','Vendedores, preparadores, embaladores y cajeros.',A.can('SETTINGS_MANAGE')?button('Nuevo responsable','staffNew',true):'')+`<div class="card"><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Funciones</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${E(x.name)}</strong></td><td>${x.roles.map(r=>E(roles[r])).join(' · ')}</td><td>${badge(x.active?'Activo':'Inactivo',x.active)}</td><td>${A.can('SETTINGS_MANAGE')?`<button type="button" class="btn secondary small" data-staff-edit="${E(x.id)}">Editar</button>`:'—'}</td></tr>`).join('')||empty(4)}</tbody></table></div></div>`;on('#staffNew',()=>staffModal());$$('[data-staff-edit]').forEach(b=>b.addEventListener('click',()=>staffModal(rows.find(x=>x.id===b.dataset.staffEdit))));}
  function staffModal(x={}){A.openModal(x.id?'Editar responsable':'Nuevo responsable',`<div class="retail-form"><label>Nombre<input name="name" maxlength="120" value="${E(x.name||'')}" required></label><div class="retail-role-list">${Object.entries(roles).map(([code,name])=>`<label><input type="checkbox" name="staff_role" value="${code}" ${(x.roles||['SELLER']).includes(code)?'checked':''}>${name}</label>`).join('')}</div><label class="toggle-card"><input name="active" type="checkbox" ${x.active!==false?'checked':''}><span><strong>Activo</strong></span></label></div>`,async fd=>{await api('staff.save',{id:x.id,name:fd.get('name'),roles:fd.getAll('staff_role'),active:fd.get('active')==='on'});return {toast:'Responsable guardado'};});}
  async function prices(){const r=await api('prices.list');$('#content').innerHTML=head('Listas de precios','Precios con IVA por unidad base, aplicados desde el Maestro.',A.can('PRODUCT_MANAGE')?button('Nueva lista','priceNew',true):'')+`<div class="card"><div class="table-wrap"><table><thead><tr><th>Lista</th><th>Productos con precio propio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td><strong>${E(x.name)}</strong></td><td>${x.item_count??(r.items||[]).filter(i=>i.price_list_id===x.id).length}</td><td>${badge(x.active?'Activa':'Inactiva',x.active)}</td><td>${A.can('PRODUCT_MANAGE')?`<button type="button" class="btn secondary small" data-price-edit="${E(x.id)}">Editar</button>`:'—'}</td></tr>`).join('')||empty(4)}</tbody></table></div></div>`;on('#priceNew',()=>priceModal({},[]));$$('[data-price-edit]').forEach(b=>b.addEventListener('click',guarded(()=>priceModal(r.rows.find(x=>x.id===b.dataset.priceEdit),(r.items||[]).filter(i=>i.price_list_id===b.dataset.priceEdit)))));}
  async function priceModal(x,items){const products=(await api('products.list',{product_kind:'PRODUCT',limit:500})).rows;if(x.id)items=(await api('prices.items',{id:x.id,product_ids:products.map(p=>p.id)})).items;const priceMap=new Map(items.map(i=>[i.product_id,i.price]));A.openModal(x.id?'Editar lista':'Nueva lista de precios',`<div class="retail-form"><label>Nombre de lista<input name="name" maxlength="120" value="${E(x.name||'')}" required></label><label class="toggle-card"><input name="active" type="checkbox" ${x.active!==false?'checked':''}><span><strong>Lista activa</strong></span></label><p class="master-help">Deja el precio vacío para usar el precio base del Maestro.</p><div class="price-product-list table-wrap"><table><thead><tr><th>Producto</th><th>Precio base</th><th>Precio de lista</th></tr></thead><tbody>${products.map(p=>`<tr><td>${E(p.name)}<small class="cell-sub">${E(p.sku)} / ${E(p.unit)}</small></td><td>${money(p.price)}</td><td><input type="number" data-list-price="${E(p.id)}" min="0" step="0.0001" value="${E(priceMap.get(p.id)??'')}" aria-label="Precio para ${E(p.name)}"></td></tr>`).join('')}</tbody></table></div></div>`,async fd=>{const visible=$$('[data-list-price]').filter(i=>i.value!=='').map(i=>({product_id:i.dataset.listPrice,price:Number(i.value)})),remove=$$('[data-list-price]').filter(i=>i.value===''&&priceMap.has(i.dataset.listPrice)).map(i=>i.dataset.listPrice);await api('prices.save',{id:x.id,name:fd.get('name'),active:fd.get('active')==='on',items:visible,remove_product_ids:remove});return {toast:'Lista de precios guardada'};});}
  async function books(){
    const today=localDate();$('#content').innerHTML=head('Libros y mayor auxiliar','Documentos emitidos, compras confirmadas y asientos para conciliación.',A.can('RCV_MANAGE')?button('Importar RCV del SII','bookImport'):'' )+`<div class="card"><div class="retail-filters"><label>Registro<select id="bookKind"><option value="SALES">Ventas / DTE</option><option value="PURCHASES">Compras</option><option value="LEDGER">Mayor y auxiliares</option><option value="RCV_SALES">RCV ventas · conciliación</option><option value="RCV_PURCHASES">RCV compras · conciliación</option></select></label><label>Desde<input id="bookFrom" type="date" value="${today.slice(0,7)}-01"></label><label>Hasta<input id="bookTo" type="date" value="${today}"></label><label>Ambiente DTE<select id="bookEnv"><option value="PRODUCCION">Producción</option><option value="PRUEBA">Prueba</option></select></label><label id="bookAccountLabel" class="hidden">Cuenta<select id="bookAccount"><option value="">Todas</option>${Object.entries(accountNames).map(([id,n])=>`<option value="${id}">${id} · ${n}</option>`).join('')}</select></label><label id="bookCustomerLabel" class="hidden">Cliente<select id="bookCustomer"><option value="">Todos</option></select></label>${button('Consultar','bookLoad',true)}${button('Exportar CSV','bookExport')}</div><div id="bookData"></div></div>`;
    if(A.can('CUSTOMER_VIEW')){const c=await api('customers.list',{limit:500});$('#bookCustomer').innerHTML=options(c.rows,null,'Todos');}
    let exported=[],headers=[];
    const load=async()=>{const kind=$('#bookKind').value,r=await api('books.list',{kind,from:$('#bookFrom').value,to:$('#bookTo').value,environment:$('#bookEnv').value,customer_id:$('#bookCustomer').value||null});let rows=r.rows;const notice=r.truncated?'<div class="retail-note warn">El período supera 5.000 registros. Reduce el rango de fechas para completar la consulta.</div>':'';
      if(kind==='LEDGER'){const acct=$('#bookAccount').value;rows=rows.flatMap(j=>(j.lines||[]).filter(l=>!acct||l.account===acct).map(l=>({...l,entry_date:j.entry_date,description:j.description}))).sort((a,b)=>a.entry_date.localeCompare(b.entry_date)||Number(a.id)-Number(b.id));headers=['Fecha','Referencia','Cuenta','Nombre cuenta','Debe','Haber'];exported=rows.map(x=>[x.entry_date,x.description,x.account,accountNames[x.account]||x.account,x.debit,x.credit]);const debit=rows.reduce((s,x)=>s+Number(x.debit),0),credit=rows.reduce((s,x)=>s+Number(x.credit),0);$('#bookData').innerHTML=notice+`<div class="retail-metric-grid"><div class="card"><span>Debe</span><strong>${money(debit)}</strong></div><div class="card"><span>Haber</span><strong>${money(credit)}</strong></div><div class="card"><span>Saldo del período</span><strong>${money(debit-credit)}</strong></div></div>`+table(headers,exported);}
      else{headers=['Fecha','Tipo','Folio / referencia','RUT','Razón social','Neto','Exento','IVA','Total'];exported=rows.map(x=>{const sign=x.sign||1;return [x.issue_date,(kind==='SALES'||kind.startsWith('RCV_'))?x.document_type:x.metadata?.receipt_type||'Compra',x.folio||x.metadata?.external_number||x.number,x.recipient_rut||x.supplier?.rut,x.recipient_name||x.supplier?.legal_name,sign*Number(x.net),sign*Number(x.exempt),sign*Number(x.tax),sign*Number(x.total)];});if(kind.startsWith('RCV_')){headers.push('Conciliación','Diferencia');exported=exported.map((row,i)=>[...row,rows[i].reconciliation,rows[i].difference??'']);}const total=exported.reduce((s,row)=>s+row[8],0);$('#bookData').innerHTML=notice+`<div class="pos-total"><span>Total del período</span><strong>${money(total)}</strong></div>`+table(headers,exported);}};
    const sync=()=>{const ledger=$('#bookKind').value==='LEDGER';$('#bookAccountLabel').classList.toggle('hidden',!ledger);$('#bookCustomerLabel').classList.toggle('hidden',!ledger);};$('#bookKind').addEventListener('change',sync);on('#bookImport',importRcv);on('#bookLoad',load);on('#bookExport',()=>exportCsv('SiasCloud_Registro.csv',headers,exported));await load();
  }
  function importRcv(){A.openModal('Importar RCV del SII',`<div class="retail-form"><label>Registro<select name="book"><option value="SALES">Ventas</option><option value="PURCHASES">Compras</option></select></label><label>Archivo CSV descargado del SII<input name="csv" type="file" accept=".csv,text/csv" required></label><p class="master-help">Se reconocen los encabezados Tipo Doc, Folio, RUT, Fecha Docto y montos. Importar de nuevo actualiza las mismas referencias.</p></div>`,async fd=>{const file=fd.get('csv');if(!file?.size)throw new Error('Selecciona el CSV');if(file.size>8*1024*1024)throw new Error('El archivo supera 8 MB');const rows=C.rcvRows(await file.text());if(!rows.length||rows.length>5000)throw new Error('Importa entre 1 y 5.000 documentos por archivo');const r=await api('rcv.import',{book:fd.get('book'),rows});return {toast:`${r.imported} documentos importados`,afterSave:()=>{const select=$('#bookKind');if(select){select.value='RCV_'+fd.get('book');select.dispatchEvent(new Event('change'));$('#bookLoad').click();}}};},'Importar y conciliar');}
  const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${E(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${E(typeof v==='number'?qty(v):v)}</td>`).join('')}</tr>`).join('')||empty(headers.length)}</tbody></table></div>`;
  function masterFields(x,products=[],suppliers=[]){return `<div class="form-section"><h4>Maestro, variantes y embalaje</h4><div class="form-grid"><label>Producto padre<select name="parent_product_id">${options(products.filter(p=>p.id!==x.id&&!p.parent_product_id),x.parent_product_id,'Producto independiente')}</select></label><label>Marca<input name="brand" value="${E(x.brand||'')}"></label><label>Proveedor principal<select name="supplier_id">${options(suppliers,x.supplier_id,'Sin asignar')}</select></label><label>Cantidad base por caja<input name="pack_quantity" type="number" min="0.0001" step="0.0001" value="${E(x.pack_quantity??'')}"></label><label>Cajas por pallet<input name="pallet_boxes" type="number" min="1" step="1" value="${E(x.pallet_boxes??'')}"></label><label class="toggle-card"><input name="fractional" type="checkbox" ${x.fractional?'checked':''}><span><strong>Permitir fracciones de unidad</strong></span></label></div><p class="master-help">La cantidad por caja se expresa en la unidad base. Ejemplo: caja de 12 kg → 12; pallet de 20 cajas → 240 kg. KG y GR se convierten automáticamente.</p><div class="retail-dimensions">${[['weight_kg','Peso (kg)'],['length_cm','Largo (cm)'],['width_cm','Ancho (cm)'],['height_cm','Alto (cm)']].map(([k,n])=>`<label>${n}<input name="${k}" type="number" min="0" step="0.0001" value="${E(x[k]??'')}"></label>`).join('')}</div><div class="toolbar"><h4>Atributos de la variante</h4>${button('Agregar atributo','masterAddAttribute')}</div><div class="retail-attributes" id="masterAttributes">${Object.entries(x.attributes||{}).map(([key,value])=>attributeHtml(key,value)).join('')}</div></div>`;}
  const attributeHtml=(key='',value='')=>`<div class="retail-attribute"><input class="attribute-key" aria-label="Nombre atributo" placeholder="Color / tamaño…" maxlength="80" value="${E(key)}"><input class="attribute-value" aria-label="Valor atributo" placeholder="Valor" maxlength="160" value="${E(value)}"><button type="button" class="icon-btn attribute-remove" aria-label="Quitar atributo">×</button></div>`;
  function bindMaster(){const bind=()=>$$('.attribute-remove').forEach(b=>b.onclick=()=>b.closest('.retail-attribute').remove());on('#masterAddAttribute',()=>{$('#masterAttributes').insertAdjacentHTML('beforeend',attributeHtml());bind();});bind();}
  function collectMaster(fd){const values={attributes:{},fractional:fd.get('fractional')==='on'};for(const key of ['parent_product_id','supplier_id','brand'])values[key]=String(fd.get(key)||'')||null;for(const key of ['pack_quantity','pallet_boxes','weight_kg','length_cm','width_cm','height_cm'])values[key]=fd.get(key)===''?null:Number(fd.get(key));$$('.retail-attribute').forEach(row=>{const key=$('.attribute-key',row).value.trim(),value=$('.attribute-value',row).value.trim();if(key){if(Object.hasOwn(values.attributes,key))throw new Error('Hay atributos con nombre repetido');Object.defineProperty(values.attributes,key,{value,enumerable:true});}});return values;}
  async function productHistory(id){const r=await api('products.history',{product_id:id});const fieldNames={name:'Nombre',sku:'SKU',barcode:'Código de barras',unit:'Unidad',price:'Precio',cost:'Costo',wholesale_price:'Precio mayorista',category:'Categoría',pack_quantity:'Cantidad por caja',pallet_boxes:'Cajas por pallet',parent_product_id:'Producto padre',active:'Activo',fractional:'Fracciones',brand:'Marca',weight_kg:'Peso'};const rows=r.rows.map(x=>[A.fmtDate(x.created_at),x.before_value?'Edición':'Creación',Object.entries(fieldNames).filter(([key])=>JSON.stringify(x.before_value?.[key])!==JSON.stringify(x.after_value?.[key])).map(([key,name])=>`${name}: ${x.after_value[key]??'—'}`).join(' · ')]);readModal('Historial del Maestro',table(['Fecha','Cambio','Detalle'],rows));}
  async function operational(id){const [r,s]=await Promise.all([api('documents.get',{id}),api('staff.list')]),d=r.document;A.openModal(`Responsables · ${d.number}`,`<div class="retail-form">${[['seller_id','SELLER'],['preparer_id','PREPARER'],['packer_id','PACKER']].map(([field,role])=>`<label>${roles[role]}<select name="${field}">${options(s.rows.filter(x=>x.active&&x.roles.includes(role)),d.metadata?.[field],'Sin asignar')}</select></label>`).join('')}<label>Notas de operación<textarea name="notes" rows="3">${E(d.notes||'')}</textarea></label>${d.status!=='DRAFT'?'<label>Motivo de la corrección<textarea name="reason" minlength="8" required></textarea></label>':''}</div>`,async fd=>{await api('documents.operational',{id,patch:Object.fromEntries([...fd].filter(([k])=>k!=='reason')),reason:fd.get('reason')||''});return {toast:'Datos operativos actualizados'};});}
  async function flow(id){const r=await api('documents.flow',{id});readModal('Flujo del documento',`<div class="retail-flow">${r.rows.map(d=>`<div class="retail-flow-step"><div><strong>${E(labels[d.document_type]||d.document_type)} · ${E(d.number)}</strong><small>${E(d.metadata?.flow_state==='CLOSED'?'Flujo cerrado':status[d.status]||d.status)} · ${money(d.total)}</small></div><button type="button" class="btn secondary small" data-flow-document="${E(d.id)}">Ver</button></div>`).join('')}</div>`);$$('[data-flow-document]').forEach(b=>b.addEventListener('click',guarded(()=>window.SiasOperations.preview(b.dataset.flowDocument))));}
  async function closeFlow(id){await api('documents.close',{id});A.closeModal(true);await A.render();A.toast('Flujo documental cerrado');}
  async function print(id,format='AUTO'){
    const normalized=String(format||'AUTO').toUpperCase()==='80'?'80MM':String(format||'AUTO').toUpperCase()==='58'?'58MM':String(format||'AUTO').toUpperCase();
    return window.SiasOperations.printDocument(id,normalized==='AUTO'&&A.state.route==='pos'?'POS_AUTO':normalized);
  }

  window.SiasRetail={init:value=>{A=value;window.SiasPos.init({...value,openCash,print});},pos,cash,movements,credits,staff,prices,books,masterFields,bindMaster,collectMaster,productHistory,operational,flow,closeFlow,print};
})();
